version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    env_file:
      - .env
    links:
      - mongodb
    networks:
      scraper:
        ipv4_address: 172.21.0.25

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: hexatone
    volumes:
      - ./Docker/mongo:/scripts
      - mongodb-data:/data/db
    networks:
      scraper:
        ipv4_address: 172.21.0.20
    ports:
      - "27017:27017"

  mongodb-graylog:
    image: mongo
    volumes:
      - mongo_graylog_data:/data/db
    networks:
      scraper:
        ipv4_address: 172.21.0.50
    ports:
      - "27080:27017"
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - http.host=172.21.0.60
      - transport.host=localhost
      - network.host=172.21.0.60
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      scraper:
        ipv4_address: 172.21.0.60
  # Graylog: https://hub.docker.com/r/graylog/graylog/

  graylog:
    image: graylog/graylog:4.0
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.21.0.35:9000/
      - DISABLE_TELEMETRY=1
      - GRAYLOG_ELASTICSEARCH_CLUSTER_NAME=elasticsearch
      - GRAYLOG_MONGODB_SERVICE_NAME_PORT=mongodb-graylog
      - GRAYLOG_MONGODB_URI=mongodb://172.21.0.50:27017/graylog
      - GRAYLOG_MONGODB_BIND_PORT=27080
      - GRAYLOG_MONGODB_BIND_IP=172.21.0.50
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      scraper:
        ipv4_address: 172.21.0.35
    depends_on:
      - mongodb-graylog
      - elasticsearch
    ports:
      # Containers should only listen on 127.0.0.1, Apache is our TLS proxy
      # Graylog web interface and REST API
      - "9000:9000"
      # Syslog TCP
      # - 1514:1514
      # Syslog UDP
      # - 1514:1514/udp
      # GELF TCP
      # - 12201:12201
      # GELF UDP
      # - 12201:12201/udp
      # GELF HTTP
      - "12202:12202"

volumes:
  mongo_cluster:
  mongo_graylog_data:
  mongodb-data:
  es_data:
  graylog_data:

networks:
  scraper:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16